// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB965ytbdzqyVGqMno4x5thf3XTEwtPP8',
    appId: '1:126258513899:web:1102c5b16eab9a83ca7bae',
    messagingSenderId: '126258513899',
    projectId: 'learn-sphere-703fa',
    authDomain: 'learn-sphere-703fa.firebaseapp.com',
    storageBucket: 'learn-sphere-703fa.firebasestorage.app',
    measurementId: 'G-JNM6HGRR90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqE5cIEOoeZMB1CNNtQC_Au8Yrv-oW2ZM',
    appId: '1:126258513899:android:f03ceda88ef90558ca7bae',
    messagingSenderId: '126258513899',
    projectId: 'learn-sphere-703fa',
    storageBucket: 'learn-sphere-703fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRFmT3VXkw5SOjoQaJ76NsP00ewSeX-8',
    appId: '1:126258513899:ios:24c44fc2783bb69cca7bae',
    messagingSenderId: '126258513899',
    projectId: 'learn-sphere-703fa',
    storageBucket: 'learn-sphere-703fa.firebasestorage.app',
    iosBundleId: 'com.example.learnsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:126258513899:ios:24c44fc2783bb69cca7bae',
    messagingSenderId: '126258513899',
    projectId: 'learn-sphere-703fa',
    storageBucket: 'learn-sphere-703fa.firebasestorage.app',
    iosBundleId: 'com.example.learnsphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:126258513899:web:4b0c53f3580d4839ca7bae',
    messagingSenderId: '126258513899',
    projectId: 'learn-sphere-703fa',
    authDomain: 'learn-sphere-703fa.firebaseapp.com',
    storageBucket: 'learn-sphere-703fa.firebasestorage.app',
    measurementId: 'G-7KRE181NGE',
  );
}
